name: vetmate
description: "VetMate - Your Trusted Pet Healthcare Companion"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.1

  # Local Storage & Session Management
  flutter_secure_storage: ^9.2.2

  # Location
  geolocator: ^12.0.0

  # UI & Design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1

  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.5
  geocoding: ^4.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"

